

import time
def index():
        html = """
<html><head>
<title>mod_python.publisher first html page</title>
</head>
<body>
<h1>This page was generated by mod_python.publisher</h1><hr>
The local time of this server is:  %s
<br>The timezone of this server is  :  %s
</body>
</html>
""" % (time.ctime(time.time()), time.timezone/3600)
        return html

		
	